### ISSUE TITLE
How to have files needing ~4 hours to generate to be provided as part of nightly CI/CD? 

### ISSUE THREAD

**Issue by GeorgeS2019** [niklas2902/py4godot#51]
> Please note that this takes a while (4 hours for me). 

How could users avoid this 4 hours pain?

**Comment by niklas2902** [comment]
I'm sorry, I will look into this. It is a bit unfortunate, because I need Cython to compile code for all 800+ classes exposed by Godot and that is what takes so long. In the past I failed to combine all classes into a single file due to memory restrictions.
I will try to create a minimal version with only 50 or 100 classes. This should make everything more workable

**Comment by sairam4123** [comment]
> > Please note that this takes a while (4 hours for me).
> 
> How could users avoid this 4 hours pain?

You could probably try caching those files and reuse them?

**Comment by niklas2902** [comment]
I implemented now a build for less files and use caching.
